name: Deploy to GoDaddy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Backup current deployment
        run: |
          ssh rahulsharma@godaddy-server 'cp -r /home/tn3uxjhb27o9/public_html/outrightstrength.com /home/tn3uxjhb27o9/public_html/outrightstrength.com_backup_$(date +%Y%m%d%H%M%S)'

      - name: Copy files to GoDaddy server
        run: |
          scp -r . rahulsharma@godaddy-server:/home/tn3uxjhb27o9/public_html/outrightstrength.com

      - name: Execute deployment script
        run: |
          ssh rahulsharma@godaddy-server << 'EOF'
            cd /home/tn3uxjhb27o9/public_html/outrightstrength.com
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            chmod -R 775 storage
            chmod -R 775 bootstrap/cache
            echo "Deployment complete."
          EOF
